//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationJedi.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JediWS", Namespace="http://schemas.datacontract.org/2004/07/WCFJedi")]
    [System.SerializableAttribute()]
    public partial class JediWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApplicationJedi.ServiceReference.CaracteristiqueWS> CaracteristiquesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSithField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApplicationJedi.ServiceReference.CaracteristiqueWS> Caracteristiques {
            get {
                return this.CaracteristiquesField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteristiquesField, value) != true)) {
                    this.CaracteristiquesField = value;
                    this.RaisePropertyChanged("Caracteristiques");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSith {
            get {
                return this.IsSithField;
            }
            set {
                if ((this.IsSithField.Equals(value) != true)) {
                    this.IsSithField = value;
                    this.RaisePropertyChanged("IsSith");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaracteristiqueWS", Namespace="http://schemas.datacontract.org/2004/07/WCFJedi")]
    [System.SerializableAttribute()]
    public partial class CaracteristiqueWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationJedi.ServiceReference.EDefCaracteristique DefinitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValeurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationJedi.ServiceReference.EDefCaracteristique Definition {
            get {
                return this.DefinitionField;
            }
            set {
                if ((this.DefinitionField.Equals(value) != true)) {
                    this.DefinitionField = value;
                    this.RaisePropertyChanged("Definition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valeur {
            get {
                return this.ValeurField;
            }
            set {
                if ((this.ValeurField.Equals(value) != true)) {
                    this.ValeurField = value;
                    this.RaisePropertyChanged("Valeur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDefCaracteristique", Namespace="http://schemas.datacontract.org/2004/07/EntitiesLayer")]
    public enum EDefCaracteristique : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Strength = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dexterity = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Perception = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StadeWS", Namespace="http://schemas.datacontract.org/2004/07/WCFJedi")]
    [System.SerializableAttribute()]
    public partial class StadeWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApplicationJedi.ServiceReference.CaracteristiqueWS> CaracteristiquesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbPlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaneteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApplicationJedi.ServiceReference.CaracteristiqueWS> Caracteristiques {
            get {
                return this.CaracteristiquesField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteristiquesField, value) != true)) {
                    this.CaracteristiquesField = value;
                    this.RaisePropertyChanged("Caracteristiques");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbPlaces {
            get {
                return this.NbPlacesField;
            }
            set {
                if ((this.NbPlacesField.Equals(value) != true)) {
                    this.NbPlacesField = value;
                    this.RaisePropertyChanged("NbPlaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Planete {
            get {
                return this.PlaneteField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaneteField, value) != true)) {
                    this.PlaneteField = value;
                    this.RaisePropertyChanged("Planete");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchWS", Namespace="http://schemas.datacontract.org/2004/07/WCFJedi")]
    [System.SerializableAttribute()]
    public partial class MatchWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationJedi.ServiceReference.JediWS Jedi1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationJedi.ServiceReference.JediWS Jedi2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationJedi.ServiceReference.JediWS JediVainqueurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationJedi.ServiceReference.EPhaseTournoi PhaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplicationJedi.ServiceReference.StadeWS StadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationJedi.ServiceReference.JediWS Jedi1 {
            get {
                return this.Jedi1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Jedi1Field, value) != true)) {
                    this.Jedi1Field = value;
                    this.RaisePropertyChanged("Jedi1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationJedi.ServiceReference.JediWS Jedi2 {
            get {
                return this.Jedi2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Jedi2Field, value) != true)) {
                    this.Jedi2Field = value;
                    this.RaisePropertyChanged("Jedi2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationJedi.ServiceReference.JediWS JediVainqueur {
            get {
                return this.JediVainqueurField;
            }
            set {
                if ((object.ReferenceEquals(this.JediVainqueurField, value) != true)) {
                    this.JediVainqueurField = value;
                    this.RaisePropertyChanged("JediVainqueur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationJedi.ServiceReference.EPhaseTournoi Phase {
            get {
                return this.PhaseField;
            }
            set {
                if ((this.PhaseField.Equals(value) != true)) {
                    this.PhaseField = value;
                    this.RaisePropertyChanged("Phase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplicationJedi.ServiceReference.StadeWS Stade {
            get {
                return this.StadeField;
            }
            set {
                if ((object.ReferenceEquals(this.StadeField, value) != true)) {
                    this.StadeField = value;
                    this.RaisePropertyChanged("Stade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPhaseTournoi", Namespace="http://schemas.datacontract.org/2004/07/EntitiesLayer")]
    public enum EPhaseTournoi : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HuitiemeFinale1 = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HuitiemeFinale2 = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HuitiemeFinale3 = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HuitiemeFinale4 = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HuitiemeFinale5 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HuitiemeFinale6 = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HuitiemeFinale7 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HuitiemeFinale8 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuartFinale1 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuartFinale2 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuartFinale3 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuartFinale4 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DemiFinale1 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DemiFinale2 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finale = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TournoiWS", Namespace="http://schemas.datacontract.org/2004/07/WCFJedi")]
    [System.SerializableAttribute()]
    public partial class TournoiWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApplicationJedi.ServiceReference.MatchWS> MatchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApplicationJedi.ServiceReference.MatchWS> Matches {
            get {
                return this.MatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchesField, value) != true)) {
                    this.MatchesField = value;
                    this.RaisePropertyChanged("Matches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getJedis", ReplyAction="http://tempuri.org/IService/getJedisResponse")]
        System.Collections.Generic.List<WebApplicationJedi.ServiceReference.JediWS> getJedis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getJedis", ReplyAction="http://tempuri.org/IService/getJedisResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplicationJedi.ServiceReference.JediWS>> getJedisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getStades", ReplyAction="http://tempuri.org/IService/getStadesResponse")]
        System.Collections.Generic.List<WebApplicationJedi.ServiceReference.StadeWS> getStades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getStades", ReplyAction="http://tempuri.org/IService/getStadesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplicationJedi.ServiceReference.StadeWS>> getStadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMatches", ReplyAction="http://tempuri.org/IService/getMatchesResponse")]
        System.Collections.Generic.List<WebApplicationJedi.ServiceReference.MatchWS> getMatches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMatches", ReplyAction="http://tempuri.org/IService/getMatchesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplicationJedi.ServiceReference.MatchWS>> getMatchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getTournois", ReplyAction="http://tempuri.org/IService/getTournoisResponse")]
        System.Collections.Generic.List<WebApplicationJedi.ServiceReference.TournoiWS> getTournois();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getTournois", ReplyAction="http://tempuri.org/IService/getTournoisResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplicationJedi.ServiceReference.TournoiWS>> getTournoisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCaracteristiquesOf", ReplyAction="http://tempuri.org/IService/getCaracteristiquesOfResponse")]
        System.Collections.Generic.List<WebApplicationJedi.ServiceReference.CaracteristiqueWS> getCaracteristiquesOf(string jediName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCaracteristiquesOf", ReplyAction="http://tempuri.org/IService/getCaracteristiquesOfResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplicationJedi.ServiceReference.CaracteristiqueWS>> getCaracteristiquesOfAsync(string jediName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addJedi", ReplyAction="http://tempuri.org/IService/addJediResponse")]
        bool addJedi(WebApplicationJedi.ServiceReference.JediWS jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addJedi", ReplyAction="http://tempuri.org/IService/addJediResponse")]
        System.Threading.Tasks.Task<bool> addJediAsync(WebApplicationJedi.ServiceReference.JediWS jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addStade", ReplyAction="http://tempuri.org/IService/addStadeResponse")]
        bool addStade(WebApplicationJedi.ServiceReference.StadeWS stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addStade", ReplyAction="http://tempuri.org/IService/addStadeResponse")]
        System.Threading.Tasks.Task<bool> addStadeAsync(WebApplicationJedi.ServiceReference.StadeWS stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addMatch", ReplyAction="http://tempuri.org/IService/addMatchResponse")]
        bool addMatch(WebApplicationJedi.ServiceReference.MatchWS match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addMatch", ReplyAction="http://tempuri.org/IService/addMatchResponse")]
        System.Threading.Tasks.Task<bool> addMatchAsync(WebApplicationJedi.ServiceReference.MatchWS match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addTournoi", ReplyAction="http://tempuri.org/IService/addTournoiResponse")]
        bool addTournoi(WebApplicationJedi.ServiceReference.TournoiWS tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addTournoi", ReplyAction="http://tempuri.org/IService/addTournoiResponse")]
        System.Threading.Tasks.Task<bool> addTournoiAsync(WebApplicationJedi.ServiceReference.TournoiWS tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateJedi", ReplyAction="http://tempuri.org/IService/updateJediResponse")]
        bool updateJedi(WebApplicationJedi.ServiceReference.JediWS jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateJedi", ReplyAction="http://tempuri.org/IService/updateJediResponse")]
        System.Threading.Tasks.Task<bool> updateJediAsync(WebApplicationJedi.ServiceReference.JediWS jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateStade", ReplyAction="http://tempuri.org/IService/updateStadeResponse")]
        bool updateStade(WebApplicationJedi.ServiceReference.StadeWS stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateStade", ReplyAction="http://tempuri.org/IService/updateStadeResponse")]
        System.Threading.Tasks.Task<bool> updateStadeAsync(WebApplicationJedi.ServiceReference.StadeWS stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateMatch", ReplyAction="http://tempuri.org/IService/updateMatchResponse")]
        bool updateMatch(WebApplicationJedi.ServiceReference.MatchWS match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateMatch", ReplyAction="http://tempuri.org/IService/updateMatchResponse")]
        System.Threading.Tasks.Task<bool> updateMatchAsync(WebApplicationJedi.ServiceReference.MatchWS match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateTournoi", ReplyAction="http://tempuri.org/IService/updateTournoiResponse")]
        bool updateTournoi(WebApplicationJedi.ServiceReference.TournoiWS tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateTournoi", ReplyAction="http://tempuri.org/IService/updateTournoiResponse")]
        System.Threading.Tasks.Task<bool> updateTournoiAsync(WebApplicationJedi.ServiceReference.TournoiWS tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/removeJedi", ReplyAction="http://tempuri.org/IService/removeJediResponse")]
        bool removeJedi(WebApplicationJedi.ServiceReference.JediWS jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/removeJedi", ReplyAction="http://tempuri.org/IService/removeJediResponse")]
        System.Threading.Tasks.Task<bool> removeJediAsync(WebApplicationJedi.ServiceReference.JediWS jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/removeStade", ReplyAction="http://tempuri.org/IService/removeStadeResponse")]
        bool removeStade(WebApplicationJedi.ServiceReference.StadeWS stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/removeStade", ReplyAction="http://tempuri.org/IService/removeStadeResponse")]
        System.Threading.Tasks.Task<bool> removeStadeAsync(WebApplicationJedi.ServiceReference.StadeWS stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/removeMatch", ReplyAction="http://tempuri.org/IService/removeMatchResponse")]
        bool removeMatch(WebApplicationJedi.ServiceReference.MatchWS match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/removeMatch", ReplyAction="http://tempuri.org/IService/removeMatchResponse")]
        System.Threading.Tasks.Task<bool> removeMatchAsync(WebApplicationJedi.ServiceReference.MatchWS match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/removeTournoi", ReplyAction="http://tempuri.org/IService/removeTournoiResponse")]
        bool removeTournoi(WebApplicationJedi.ServiceReference.TournoiWS tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/removeTournoi", ReplyAction="http://tempuri.org/IService/removeTournoiResponse")]
        System.Threading.Tasks.Task<bool> removeTournoiAsync(WebApplicationJedi.ServiceReference.TournoiWS tournoi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebApplicationJedi.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebApplicationJedi.ServiceReference.IService>, WebApplicationJedi.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WebApplicationJedi.ServiceReference.JediWS> getJedis() {
            return base.Channel.getJedis();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplicationJedi.ServiceReference.JediWS>> getJedisAsync() {
            return base.Channel.getJedisAsync();
        }
        
        public System.Collections.Generic.List<WebApplicationJedi.ServiceReference.StadeWS> getStades() {
            return base.Channel.getStades();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplicationJedi.ServiceReference.StadeWS>> getStadesAsync() {
            return base.Channel.getStadesAsync();
        }
        
        public System.Collections.Generic.List<WebApplicationJedi.ServiceReference.MatchWS> getMatches() {
            return base.Channel.getMatches();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplicationJedi.ServiceReference.MatchWS>> getMatchesAsync() {
            return base.Channel.getMatchesAsync();
        }
        
        public System.Collections.Generic.List<WebApplicationJedi.ServiceReference.TournoiWS> getTournois() {
            return base.Channel.getTournois();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplicationJedi.ServiceReference.TournoiWS>> getTournoisAsync() {
            return base.Channel.getTournoisAsync();
        }
        
        public System.Collections.Generic.List<WebApplicationJedi.ServiceReference.CaracteristiqueWS> getCaracteristiquesOf(string jediName) {
            return base.Channel.getCaracteristiquesOf(jediName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebApplicationJedi.ServiceReference.CaracteristiqueWS>> getCaracteristiquesOfAsync(string jediName) {
            return base.Channel.getCaracteristiquesOfAsync(jediName);
        }
        
        public bool addJedi(WebApplicationJedi.ServiceReference.JediWS jedi) {
            return base.Channel.addJedi(jedi);
        }
        
        public System.Threading.Tasks.Task<bool> addJediAsync(WebApplicationJedi.ServiceReference.JediWS jedi) {
            return base.Channel.addJediAsync(jedi);
        }
        
        public bool addStade(WebApplicationJedi.ServiceReference.StadeWS stade) {
            return base.Channel.addStade(stade);
        }
        
        public System.Threading.Tasks.Task<bool> addStadeAsync(WebApplicationJedi.ServiceReference.StadeWS stade) {
            return base.Channel.addStadeAsync(stade);
        }
        
        public bool addMatch(WebApplicationJedi.ServiceReference.MatchWS match) {
            return base.Channel.addMatch(match);
        }
        
        public System.Threading.Tasks.Task<bool> addMatchAsync(WebApplicationJedi.ServiceReference.MatchWS match) {
            return base.Channel.addMatchAsync(match);
        }
        
        public bool addTournoi(WebApplicationJedi.ServiceReference.TournoiWS tournoi) {
            return base.Channel.addTournoi(tournoi);
        }
        
        public System.Threading.Tasks.Task<bool> addTournoiAsync(WebApplicationJedi.ServiceReference.TournoiWS tournoi) {
            return base.Channel.addTournoiAsync(tournoi);
        }
        
        public bool updateJedi(WebApplicationJedi.ServiceReference.JediWS jedi) {
            return base.Channel.updateJedi(jedi);
        }
        
        public System.Threading.Tasks.Task<bool> updateJediAsync(WebApplicationJedi.ServiceReference.JediWS jedi) {
            return base.Channel.updateJediAsync(jedi);
        }
        
        public bool updateStade(WebApplicationJedi.ServiceReference.StadeWS stade) {
            return base.Channel.updateStade(stade);
        }
        
        public System.Threading.Tasks.Task<bool> updateStadeAsync(WebApplicationJedi.ServiceReference.StadeWS stade) {
            return base.Channel.updateStadeAsync(stade);
        }
        
        public bool updateMatch(WebApplicationJedi.ServiceReference.MatchWS match) {
            return base.Channel.updateMatch(match);
        }
        
        public System.Threading.Tasks.Task<bool> updateMatchAsync(WebApplicationJedi.ServiceReference.MatchWS match) {
            return base.Channel.updateMatchAsync(match);
        }
        
        public bool updateTournoi(WebApplicationJedi.ServiceReference.TournoiWS tournoi) {
            return base.Channel.updateTournoi(tournoi);
        }
        
        public System.Threading.Tasks.Task<bool> updateTournoiAsync(WebApplicationJedi.ServiceReference.TournoiWS tournoi) {
            return base.Channel.updateTournoiAsync(tournoi);
        }
        
        public bool removeJedi(WebApplicationJedi.ServiceReference.JediWS jedi) {
            return base.Channel.removeJedi(jedi);
        }
        
        public System.Threading.Tasks.Task<bool> removeJediAsync(WebApplicationJedi.ServiceReference.JediWS jedi) {
            return base.Channel.removeJediAsync(jedi);
        }
        
        public bool removeStade(WebApplicationJedi.ServiceReference.StadeWS stade) {
            return base.Channel.removeStade(stade);
        }
        
        public System.Threading.Tasks.Task<bool> removeStadeAsync(WebApplicationJedi.ServiceReference.StadeWS stade) {
            return base.Channel.removeStadeAsync(stade);
        }
        
        public bool removeMatch(WebApplicationJedi.ServiceReference.MatchWS match) {
            return base.Channel.removeMatch(match);
        }
        
        public System.Threading.Tasks.Task<bool> removeMatchAsync(WebApplicationJedi.ServiceReference.MatchWS match) {
            return base.Channel.removeMatchAsync(match);
        }
        
        public bool removeTournoi(WebApplicationJedi.ServiceReference.TournoiWS tournoi) {
            return base.Channel.removeTournoi(tournoi);
        }
        
        public System.Threading.Tasks.Task<bool> removeTournoiAsync(WebApplicationJedi.ServiceReference.TournoiWS tournoi) {
            return base.Channel.removeTournoiAsync(tournoi);
        }
    }
}
